remote_theme: pmarsceill/just-the-docs

aux_links:
  "Edit on Github":
    - "//github.com/bcgov/HADF-Framework"

callcentre.md

footer_content: "<a href='https://gov.bc.ca/'>
  <img 
    src='/HADF-Framework/assets/images/BCID_H_rgb_pos.png' 
    height='42' 
    width='200' 
    style='display: block; margin-left: auto;margin-right: auto;width: 50%;' 
    alt='BC Gov'/> 
</a>"
